config/routes.rb
Rails.application.routes.draw do
  constraints(subdomain: "manage") do
    resources :songs, only: [:new, :create, :edit, :update, :destroy], controller: "manage/songs" do
      collection do
        put :publish
      end
    end

    root to: "manage/songs#index", as: "manage_root"
  end

  resources :songs, only: [:show]

  root to: "songs#index"
end

app/models/song.rb
class Song < ActiveRecord::Base
  PURCHASE_TYPES    = %w(album song).freeze
  GROUPS_PER_PAGE   = 5
  REMOTE_ATTRIBUTES = %w(id title duration artwork_url permalink_url).freeze
  LOCAL_ATTRIBUTES  = %w(
    remote_id artist title duration artwork_url permalink_url
    purchase_type purchase_url
  ).freeze

  store_accessor :data, *LOCAL_ATTRIBUTES

  scope :published,              -> { where("published_on IS NOT NULL").desc(:published_on) }
  scope :published_before,       -> (date) { where("published_on < ?", date) }
  scope :published_on_or_before, -> (date) { where("published_on <= ?", date) }
  scope :unpublished,            -> { where("published_on IS NULL").asc(:id) }

  validates :data,          presence: true
  validates :remote_id,     presence: true, numericality: { only_integer: true }
  validates :artist,        presence: true
  validates :title,         presence: true
  validates :duration,      presence: true, numericality: { only_integer: true }
  validates :artwork_url,   presence: true
  validates :permalink_url, presence: true
  validates :purchase_type, inclusion: { in: PURCHASE_TYPES }, allow_blank: true

  def self.build_from_remote(id)
    return if id.blank?

    client = SoundCloud.new(client_id: ENV["SOUNDCLOUD_ID"])
    remote = client.get("/tracks/#{id}")

    return unless remote.streamable

    Song.new.tap do |song|
      song.update_from_remote(remote)
    end
  rescue SoundCloud::ResponseError
  end

  def self.paginate(options = {})
    limit = options[:per_page] || GROUPS_PER_PAGE
    dates = distinct.published.limit(options[:per_page]).pluck(:published_on)

    unscoped.where(published_on: dates).desc(:published_on)
  end

  def self.publish!(*ids)
    transaction do
      Song.where(id: ids).each(&:publish!)
    end
  end

  def artwork_url(style = nil)
    url = data["artwork_url"]

    if style.present?
      url.sub!(%r{-large.jpg\Z}, "-#{style}.jpg")
    end

    url
  end

  def publish!
    update!(published_on: Date.today)
  end

  def update_from_remote(remote)
    self.data = remote.with_indifferent_access.tap do |data|
      artist, title = data[:title].split(" - ", 2)

      data.slice!(*REMOTE_ATTRIBUTES)
      data[:title]     = title
      data[:artist]    = artist
      data[:duration]  = (data[:duration] / 1000.0).round
      data[:remote_id] = data.delete(:id)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/manage_controller.rb
class ManageController < ApplicationController
  layout "manage"

  http_basic_authenticate_with(
    name:     ENV["MANAGE_USERNAME"],
    password: ENV["MANAGE_PASSWORD"],
    if:       -> { Rails.env.production? }
  )
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  COMPRESSOR = HtmlCompressor::Compressor.new(
    remove_intertag_spaces: true,
    remove_surrounding_spaces: HtmlCompressor::Compressor::BLOCK_TAGS_MIN
  )

  def index
    respond_to do |format|
      format.html do
        @songs = Song.published_on_or_before(Date.today).paginate
      end
      format.js do
        songs  = Song.published_before(params[:date]).paginate
        groups = songs.group_by(&:published_on)

        render text: COMPRESSOR.compress(
          render_to_string("_groups", locals: { groups: groups })
        )
      end
    end
  end

  def show
    @song  = Song.published.find(params[:id])
    @songs = Song.published_on_or_before(@song.published_on).paginate

    render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  TIPS = [
   "Use the progress bar to seek.",
   "Use <kbd>M</kbd> to mute or unmute.",
   "Use <kbd>space</kbd> to pause and play.",
   "Use <kbd>J</kbd> and <kbd>K</kbd> to navigate songs.",
   "Use <kbd>up</kbd> and <kbd>down</kbd> to adjust the volume."
  ].freeze

  def csrf_meta_tags
    [
      tag("meta", name: "csrf-param", content: request_forgery_protection_token),
      tag("meta", name: "csrf-token", content: form_authenticity_token)
    ].join("\n  ").html_safe if protect_against_forgery?
  end

  def tag(name, options = nil, open = false, escape = true)
    "<#{name}#{tag_options(options, escape)}>".html_safe
  end

  def tip
    TIPS.sample.html_safe
  end
end

app/helpers/songs_helper.rb
module SongsHelper
  def date_to_weekday(date)
    if date.today?
      "Today"
    elsif Date.yesterday == date
      "Yesterday"
    else
      date.strftime("%A")
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-US">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="New songs every day.">

  <% if @song.present? %>
    <meta name="twitter:card" content="summary">
    <meta name="twitter:site" content="@dailysongsio">
    <meta name="twitter:title" content="<%= @song.title %> by <%= @song.artist %>">
    <meta name="twitter:description" content="Listen to <%= @song.title %> and discover new songs every day.">
    <meta name="twitter:url" content="<%= song_url(@song) %>">
    <meta name="twitter:image" content="<%= @song.artwork_url(:crop) %>">
  <% else %>
    <meta name="twitter:card" content="summary">
    <meta name="twitter:site" content="@dailysongsio">
    <meta name="twitter:title" content="Daily Songs">
    <meta name="twitter:description" content="New songs every day.">
    <meta name="twitter:url" content="http://dailysongs.io">
  <% end %>

  <title>Daily Songs</title>

  <%= stylesheet_link_tag "application" %>
</head>
<body>

<section id="sidebar">
  <header>
    <a href="<%= root_path %>" class="logo">
      <h1>Daily Songs</h1>
      <p>New songs every day.</p>
    </a>

    <a href="https://twitter.com/dailysongsio" class="follow" target="_blank" rel="nofollow">
      Follow <span>@dailysongsio</span> on Twitter.
    </a>
  </header>

  <section id="player">
    <div class="tip">
      <p>
        <span>Tip</span> <%= tip %>
      </p>
    </div>
  </section>
</section>

<%= yield -%>

<footer>
  <p><a href="https://soundcloud.com" target="_blank" rel="nofollow">Powered by SoundCloud.</a></p>
</footer>

<%= yield :javascript -%>
<script>
  (function(d) {
    if ((new Detector()).detect("Proxima Nova")) {
      return;
    }

    var config = {
      kitId: "xdy7csy",
      scriptTimeout: 3000
    },
    h=d.documentElement,t=setTimeout(function(){h.className=h.className.replace(/\bwf-loading\b/g,"")+" wf-inactive";},config.scriptTimeout),tk=d.createElement("script"),f=false,s=d.getElementsByTagName("script")[0],a;h.className+=" wf-loading";tk.src="//use.typekit.net/"+config.kitId+".js";tk.async=true;tk.onload=tk.onreadystatechange=function(){a=this.readyState;if(f||a&&a!="complete"&&a!="loaded")return;f=true;clearTimeout(t);try{Typekit.load(config)}catch(e){}};s.parentNode.insertBefore(tk,s)
  })(document);
</script>
<script>
  if (window.location.hostname == "dailysongs.io") {
    (function(i,s,o,g,r,a,m){i["GoogleAnalyticsObject"]=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,"script","//www.google-analytics.com/analytics.js","ga");

    ga("create", "UA-8648594-20", "auto");
    ga("send", "pageview");
  }
</script>

</body>
</html>

app/views/layouts/manage.html.erb
<!DOCTYPE html>
<html lang="en-US">
<head>
  <meta charset="utf-8">

  <title>Daily Songs</title>

  <%= stylesheet_link_tag "application", "manage" %>
</head>
<body>

<section id="sidebar">
  <header>
    <a href="<%= root_url(subdomain: nil) %>" class="logo">
      <h1>Daily Songs</h1>
      <p>New songs every day.</p>
    </a>
  </header>
</section>

<%= yield -%>

<%= yield :javascript -%>

</body>
</html>

app/views/songs/_groups.html.erb
<% groups.each do |date, songs| %>
  <section class="group">
    <h1>
      <%= date_to_weekday(date) %>

      <time datetime="<%= date %>">
        <%= date.to_s(:ordinalized) %>
      </time>
    </h1>

    <ul>
      <% songs.each do |song| %>
        <%= content_tag("li", data: { published_on: song.published_on.to_s }.merge(song.data)) do %>
          <svg class="play" viewBox="0 0 32 32">
            <path d="M4 4 L28 16 L4 28 z"></path>
          </svg>

          <%= song.title %> <span class="byline">by <%= song.artist %></span>
        <% end %>
      <% end %>
    </ul>
  </section>
<% end %>

app/views/songs/index.html.erb
<section id="content">
  <%= render "groups", groups: @songs.group_by(&:published_on) %>
</section>

<% content_for :javascript do %>
  <%= javascript_include_tag "application" %>

  <script>
    (function() {
      var element;

      <% if @song.present? %>
        element = document.querySelector("[data-remote-id='<%== @song.remote_id %>']");

        if (element) {
          Player.play(element.dataset);
        }
      <% end %>

      element = element || document.querySelector("#content [data-remote-id]");
      element.classList.add("selected");
    })();
  </script>
<% end %>